import 'package:flutter/foundation.dart';

enum AbilityName {
  AFTERSHOCK, ALARMBOT, ASTRALFORM,
  BARRIER_ORB, BLADE_STORM, BLAST_PACK, BLAZE, BLINDSIDE, BOOM_BOT,
  CLOUDBURST, COSMIC_DIVIDE, CURVEBALL, CYBER_CAGE,
  DARK_COVER, DEVOUR, DIMENSION_DRIFT, DISMISS,
  EMPRESS,
  FAKEOUT, FAULT_LINE, FLASHPOINT, FROM_THE_SHADOWS,
  GATECRASH, GRAVITY_WALL, GUIDING_LIGHT,
  HEALING_ORB, HOT_HANDS, HUNTERS_FURY,
  INCENDIARY,
  LEER, LOCKDOWN,
  NANOSWARM, NEBULA, NEURAL_THEFT, NOVA_PULSE,
  ORBITAL_STRIKE, OWL_DRONE,
  PAINT_SHELLS, PARANOIA, POISON_CLOUD,
  RECON_BOLT, REGROWTH, RESURRECTION, ROLLING_THUNDER, RUN_IT_BACK,
  SEEKERS, SHOCK_BOLT, SHOWSTOPPER, SHROUDED_STEP, SKY_SMOKE, SLOW_ORB,
  SNAKE_BITE, SPYCAM, STIM_BEACON,
  TAILWIND, TOXIC_SCREEN, TRAILBLAZER, TRAPWIRE, TURRET,
  UPDRAFT,
  VIPERS_PIT
}

extension AbilityEx on AbilityName{
  String get inString => describeEnum(this);
}